services:
  dojo-forkserver:
    image: oostvoort/dojo-forkserver:v1.2.6
    container_name: dojo-forkserver
    ports:
      - "5050:5050"
      - "3000:3000"
      - "8080:8080"
      - "50051"
    restart: unless-stopped
    volumes:
      - ./contracts:/opt/contracts
    networks:
      - pixelaw

networks:
  pixelaw:
    driver: bridge

